// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASRayNVurMXFJZ-_u0cIbwXwg07oeP6Go',
    appId: '1:1047562975691:web:135c1ccab2f71aa9419e4e',
    messagingSenderId: '1047562975691',
    projectId: 'umarket-123ea',
    authDomain: 'umarket-123ea.firebaseapp.com',
    storageBucket: 'umarket-123ea.appspot.com',
    measurementId: 'G-ZDML0PYKWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTHWWb1TfCn40leG-GDFfaizV_nBWeDw0',
    appId: '1:1047562975691:android:3c3f60eac2318f6e419e4e',
    messagingSenderId: '1047562975691',
    projectId: 'umarket-123ea',
    storageBucket: 'umarket-123ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYIroLL2RGEZ23n6SkRNkDgXSkKdZfYxQ',
    appId: '1:1047562975691:ios:c604211e0bea49a4419e4e',
    messagingSenderId: '1047562975691',
    projectId: 'umarket-123ea',
    storageBucket: 'umarket-123ea.appspot.com',
    iosClientId: '1047562975691-4pj2bi613k0p9qo447et3nvd6uvm765k.apps.googleusercontent.com',
    iosBundleId: 'com.example.umarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYIroLL2RGEZ23n6SkRNkDgXSkKdZfYxQ',
    appId: '1:1047562975691:ios:7c27db2fe6384edd419e4e',
    messagingSenderId: '1047562975691',
    projectId: 'umarket-123ea',
    storageBucket: 'umarket-123ea.appspot.com',
    iosClientId: '1047562975691-4gdioc612bip64om2vcopvk84v22rj92.apps.googleusercontent.com',
    iosBundleId: 'com.example.umarket.RunnerTests',
  );
}
